version: '3.7'

services:
  homechatgpt:
    image: homechatgpt-image
    container_name: go_chatgpt
    build:
      context: .
      dockerfile: webApp\Dockerfile

  nginx:
     image: nginx:1.24.1
     ports:
       - 7197:7197
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./upstreams:/etc/nginx/conf.d/upstreams
       - ./locations:/etc/nginx/conf.d/locations
       - ../tools/nginx-1.24.1/conf/locations:/etc/nginx/conf.d/locations
       - ../tools/nginx-1.24.1/ssl:/etc/nginx/ssl

volumes:
  homechatgpt_volume:
    external: true
